title: Andylee - 李正辉博客
name: andylee
email: lizhenghui.dlu@gmail.com
description: 李正辉，PHP工程师，从事web相关的开发工作。开源爱好者，GitHub:https://github.com/lizhenghui。
keywords: php, golang
skill_keywords: [PHP, Javascript, HTML+CSS, Linux, Laravel, Git, Mac, RESTful, Stackoverflow, Sublime Text, OmniGaffale, OminiPlan]

timezone:    PRC
encoding: "utf-8"

url: http://lizhenghui.github.io
baseurl:  "/"
domain:    lizhenghui.github.io
permalink:     /articles/:year/:month/:title.html
paginate_path: 'page:num'
paginate:   10
source_code: https://github.com/lizhenghui/lizhenghui.github.io

# Build settings
markdown:    kramdown
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

gems:
  - jemoji
  - rouge
  # # # - jekyll-mentions
  # - jekyll-sitemap
  - jekyll-html-pipeline

disqus:
  id: overtrueme

google:
    analytics_id: UA-55452630-1

# navigation
navs:
  -
    href: /
    label: Home

  -
    href: /open-source
    label: Open-Source

  -
    href: https://github.com/lizhenghui
    label: GitHub
    target: _blank

  -
    href: http://weibo.com/zhaolizhenghui
    label: Weibo
    target: _blank

  -
    href: /bookmark
    label: Bookmark

  -
    href: /about
    label: About

popular_repos: ['php', 'golang', 'sphinx']
contribute_repos: ['flike/idgo']